name: fluttersqlitemanager
description: "A Flutter SQLite App with Image, Search, and CRUD features."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.2.8+4
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  fluttertoast: ^8.2.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
