name: fluttersqlitemanager
description: "A Flutter app with SQLite integration, image storage, search, and CRUD operations."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  image_picker: ^1.0.7
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2  # Persistent Dark Mode
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
